name: Deploy
on:
    push:
        branches: 'main'
concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

permissions:
    contents: write

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 21
                  cache: 'npm'

            - name: Clean Install
              run: npm ci

            - name: Build
              run: npm run build

            - name: Deploy
              run: npm run deploy
